:asset_root: public
:load_path:
  - app/javascripts
  - vendor/sprockets/*/src
  - vendor/plugins/*/javascripts
  - vendor/javascripts
:source_files:
  :default:
    - app/javascripts/application.js
    - app/javascripts/**/*.js
  :iphone:
    - app/javascripts/iphone/application.js
    - app/javascripts/iphone/**/*.js
